//! Host-language binding generation from a unionid schema.
//!
//! The first slice emits Rust `struct`/`enum` definitions for the named types
//! declared in a schema file so applications can bind them through the existing
//! serde-based typed API without maintaining a second copy of the model.

use std::collections::BTreeMap;
use std::fmt::Write;

use crate::error::{Error, Result};
use crate::model::{Column, EnumType, ScalarType, TypeDefinition};

const RUST_KEYWORDS: &[&str] = &[
    "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "crate",
    "do", "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "if", "impl", "in",
    "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
    "return", "self", "Self", "static", "struct", "super", "trait", "true", "try", "type",
    "typeof", "unsafe", "unsized", "use", "virtual", "where", "while", "yield",
];

/// Generate Rust type definitions for every named type in `source`.
pub fn rust(source: &str) -> Result<String> {
    let database = crate::schema::parse(source)?;
    let names = id_names(&database.catalog);
    let mut output = String::new();
    output.push_str("// Generated by `unionid schema rust`. Do not edit by hand.\n");
    output.push_str("// Add `serde` and `unionid` to the consuming crate.\n");
    output.push_str("use serde::{Deserialize, Serialize};\n\n");
    for definition in database.catalog.types.values() {
        emit_definition(&mut output, definition, &names)?;
        output.push('\n');
    }
    Ok(output)
}

fn id_names(catalog: &crate::model::Catalog) -> BTreeMap<u64, String> {
    catalog
        .types
        .values()
        .map(|definition| (definition.id, definition.name.clone()))
        .collect()
}

fn emit_definition(
    output: &mut String,
    definition: &TypeDefinition,
    names: &BTreeMap<u64, String>,
) -> Result<()> {
    let name = ident(&definition.name);
    match &definition.ty {
        ScalarType::Record(fields) => {
            writeln!(
                output,
                "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]"
            )
            .unwrap();
            writeln!(output, "pub struct {name} {{").unwrap();
            for field in fields {
                let ty = field_type(field, &definition.name, names)?;
                writeln!(output, "    pub {}: {ty},", ident(&field.name)).unwrap();
            }
            writeln!(output, "}}").unwrap();
        }
        ScalarType::Enum(sum) => emit_enum(output, &definition.name, sum, names)?,
        ScalarType::Tuple(items) => {
            let items = items
                .iter()
                .map(|item| format_type(item, names))
                .collect::<Result<Vec<_>>>()?
                .join(", ");
            writeln!(output, "/// Named tuple type `{}`.", definition.name).unwrap();
            writeln!(output, "pub type {name} = ({items});").unwrap();
        }
        other => {
            let ty = format_type(other, names)?;
            writeln!(output, "/// Named type `{}`.", definition.name).unwrap();
            writeln!(output, "pub type {name} = {ty};").unwrap();
        }
    }
    Ok(())
}

fn emit_enum(
    output: &mut String,
    owner: &str,
    sum: &EnumType,
    names: &BTreeMap<u64, String>,
) -> Result<()> {
    writeln!(
        output,
        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]"
    )
    .unwrap();
    writeln!(output, "pub enum {} {{", ident(owner)).unwrap();
    for variant in &sum.variants {
        let variant_name = ident(&variant.name);
        match variant.args.as_slice() {
            [] => {
                writeln!(output, "    {variant_name},").unwrap();
            }
            [ScalarType::Record(fields)] => {
                writeln!(output, "    {variant_name} {{").unwrap();
                for field in fields {
                    let ty = field_type(field, owner, names)?;
                    writeln!(output, "        {}: {ty},", ident(&field.name)).unwrap();
                }
                writeln!(output, "    }},").unwrap();
            }
            args => {
                let payload = args
                    .iter()
                    .map(|argument| owned_type(argument, owner, names))
                    .collect::<Result<Vec<_>>>()?
                    .join(", ");
                writeln!(output, "    {variant_name}({payload}),").unwrap();
            }
        }
    }
    writeln!(output, "}}").unwrap();
    Ok(())
}

fn field_type(field: &Column, owner: &str, names: &BTreeMap<u64, String>) -> Result<String> {
    owned_type(&field.ty, owner, names)
}

/// Format a payload type, boxing a direct self-reference so recursive types
/// compile. `list` already indirects through `Vec`, so it is never boxed.
fn owned_type(ty: &ScalarType, owner: &str, names: &BTreeMap<u64, String>) -> Result<String> {
    let rendered = format_type(ty, names)?;
    if self_referential(ty, owner, names) {
        Ok(format!("Box<{rendered}>"))
    } else {
        Ok(rendered)
    }
}

fn self_referential(ty: &ScalarType, owner: &str, names: &BTreeMap<u64, String>) -> bool {
    match ty {
        ScalarType::Ref(id) => names.get(id).is_some_and(|name| name == owner),
        ScalarType::Named(name) => name == owner,
        ScalarType::Option(inner) => self_referential(inner, owner, names),
        ScalarType::Record(fields) => fields
            .iter()
            .any(|field| self_referential(&field.ty, owner, names)),
        ScalarType::Enum(sum) => sum.variants.iter().any(|variant| {
            variant
                .args
                .iter()
                .any(|argument| self_referential(argument, owner, names))
        }),
        ScalarType::Tuple(items) => items
            .iter()
            .any(|item| self_referential(item, owner, names)),
        ScalarType::List(_) => false,
        _ => false,
    }
}

fn format_type(ty: &ScalarType, names: &BTreeMap<u64, String>) -> Result<String> {
    Ok(match ty {
        ScalarType::Int => "i64".into(),
        ScalarType::Float => "f64".into(),
        ScalarType::Bool => "bool".into(),
        ScalarType::Text => "String".into(),
        ScalarType::Uuid => "unionid::scalars::Uuid".into(),
        ScalarType::Date => "unionid::scalars::Date".into(),
        ScalarType::Timestamp => "unionid::scalars::Timestamp".into(),
        ScalarType::Duration => "unionid::scalars::Duration".into(),
        ScalarType::Decimal { .. } => "unionid::scalars::Decimal".into(),
        ScalarType::Bytes => "unionid::scalars::Bytes".into(),
        ScalarType::Option(inner) => format!("Option<{}>", format_type(inner, names)?),
        ScalarType::List(inner) => format!("Vec<{}>", format_type(inner, names)?),
        ScalarType::Tuple(items) => {
            let mut parts = items
                .iter()
                .map(|item| format_type(item, names))
                .collect::<Result<Vec<_>>>()?;
            if parts.len() == 1 {
                // A one-element tuple requires a trailing comma in Rust.
                return Ok(format!("({},)", parts.remove(0)));
            }
            format!("({})", parts.join(", "))
        }
        ScalarType::Ref(id) => names
            .get(id)
            .cloned()
            .ok_or_else(|| Error::new("E_SCHEMA", format!("unresolved type reference {id}")))?,
        ScalarType::Named(name) => name.clone(),
        ScalarType::Enum(_) | ScalarType::Record(_) => {
            return Err(Error::new(
                "E_SCHEMA",
                "anonymous record or enum types must be declared with a name to generate Rust bindings",
            ));
        }
    })
}

fn ident(name: &str) -> String {
    if RUST_KEYWORDS.contains(&name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}
